### ISSUE TITLE
code is not complete

### ISSUE THREAD

**Issue by XDWang97** [Linwei-Chen/Seg-Aliasing#3]
Thank you very much for your work. I wanted to run it on my own data set, but found that FreqFusion2encoder was missing.

**Comment by Linwei-Chen** [comment]
Thanks for your comments.
This code is built on mmsegmentation (version == 0.25.0). 
You should install mmseg first by running the following command:

```
pip install mmsegmentation==0.25.0
```

Please refer to [get_started.md](https://github.com/open-mmlab/mmsegmentation/blob/main/docs/en/get_started.md#installation) for more details about the installation process and [dataset_prepare.md](https://github.com/open-mmlab/mmsegmentation/blob/main/docs/en/user_guides/2_dataset_prepare.md#prepare-datasets) for dataset preparation instructions.
It is recommended to install mmsegmentation and mmcv-full first and then use the code. Alternatively, you can directly use the core implementation in your code at "./SegAliasing/mmseg_custom/models/backbones/resnet.py" for the proposed modules. The three types of error metrics can be found at "./SegAliasing/mmseg_custom/core/evaluation/metrics.py".
Thanks for your feedback; we have updated the README.
The FreqFusion2encoder is not part of this project, and the code has been updated accordingly.
