### ISSUE TITLE
Evaluation code for the Metric "FErr MErr DErr"

### ISSUE THREAD

**Issue by weiguangzhao** [Linwei-Chen/Seg-Aliasing#4]
Hi, thanks for the great work. I didn't find the evaluation code for the Metric "FErr MErr DErr". Since these three metrics are the key metrics to eval the three hard catergories in your paper, could you please provide the implement code？

**Comment by Linwei-Chen** [comment]
Thanks for your interest. You can find the `metrics.py` file at [this link](https://github.com/Linwei-Chen/Seg-Aliasing/blob/main/mmseg_custom/core/evaluation/metrics.py). To obtain the results, you can use the `test.py` file.

**Comment by weiguangzhao** [comment]
Hi Linwei, I didn't find the "**FErr MErr DErr**" in the metrics.py file. Beside, I have run the test.py and I still can't get the results of  Metric "FErr MErr DErr".  Could you help check out the code and release the part of  Metric "**FErr MErr DErr**"?  Thank you.

**Comment by Linwei-Chen** [comment]
You can get FErr, MErr, DErr by:
FErr = FP_rate
MErr = FN_rate
DErr = mdisplacement_rate

**Comment by Linwei-Chen** [comment]
Notice that PASCAL VOC marks the boundary as "ignore" (255), which needs to be handled carefully.

**Comment by weiguangzhao** [comment]
Got it! Thank you.
