### ISSUE TITLE
I can't find the specific code of 'class AdaFreq_Pooling'?

### ISSUE THREAD

**Issue by wakakkakak** [Linwei-Chen/Seg-Aliasing#7]
Thank you for your great contribution! 

I wonder to know that when I read the code I can't find the specific code of 'the idea of this paper-class AdaFreq_Pooling' . (In class ResNetV1cWithBlur(ResNetV1c))

Could you please tell me exactly where it is?
![屏幕截图 2024-05-08 095907](https://github.com/Linwei-Chen/Seg-Aliasing/assets/117575513/ebaddb53-d1f8-40e0-822f-01d0930445b4)

I look forward to hearing from you!

**Comment by Linwei-Chen** [comment]
Thanks for your insterets! This is not part of this work, maybe our next work hhhh, so you can just remove these lines.
