### ISSUE TITLE
Question about the De-Aliasing filter in code

### ISSUE THREAD

**Issue by CK-Sung** [Linwei-Chen/Seg-Aliasing#8]
I cannot find your methods (DAF). I see the FLC pooling, but it looks that does not use Equivalent sampling rate (ESR). 
Thank you for sharing great work!

**Comment by Linwei-Chen** [comment]
Thank you for your attention. ESR can be calculated as √2 / 2. For most modern models, we set this value directly in the code for simplicity. I will update the code to clarify this.
